name: build

on:
  push:
    branches:
      - main
  pull_request:

env:
  YONTRACK_URL: ${{ vars.YONTRACK_URL }}
  YONTRACK_TOKEN: ${{ secrets.YONTRACK_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
    steps:
      - id: checkout
        uses: actions/checkout@v4
      - id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@nemerosa'
      - id: npm-ci
        run: npm ci

      - id: npm-lint
        run: npm run lint

      - name: npm-test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run test

      - id: npm-publish
        if: ${{ github.ref == 'refs/heads/main' }}
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
